# Databricks notebook source
"""note grouping by asking chatgpt manually, can automate this if it is useful"""

# COMMAND ----------

def combine_dict(dict1, dict2):
    combined_dict = {}

    for key in dict1:
        combined_dict[key] = dict1[key]

    for key in dict2:
        if key in combined_dict:
            combined_dict[key] += dict2[key]
        else:
            combined_dict[key] = dict2[key]
    return combined_dict

# COMMAND ----------

top_notes_mapping1 = {
  "Citrus": [
    "Calabrian bergamot",
    "Orange",
    "Lemon",
    "Petitgrain",
    "Neroli",
    "Green Mandarin",
    "Yuzu",
    "Bergamot",
    "Grapefruit",
    "Chinotto",
    "Mandarin Orange",
    "Lime",
    "Citron",
    "Calabrian Mandarin",
    "Tangerine",
    "Italian Lemon",
    "Italian Mandarin",
    "Calamansi",
    "Californian Lemon",
    "Chinese Grapefruit",
    "Strawberry",
    "Lemon Zest",
    "Amalfi Lemon",
    "Tunisian Orange Blossom",
    "California Orange",
    "Sicilian Mandarin",
    "Indian Mandarin",
    "Sicilian Lemon",
    "Orange Leaf",
    "Neroli Essence"
  ],
  "Spicy": [
    "Sichuan Pepper",
    "Pepper",
    "Rosemary",
    "Basil",
    "Sage",
    "Pink Pepper",
    "Coriander",
    "Black Pepper",
    "Coriander Leaf",
    "Juniper",
    "Juniper Berries",
    "Cinnamon",
    "Cardamom",
    "Clove",
    "Caraway",
    "Guatemalan Cardamom",
    "Black Cardamom",
    "Nutmeg",
    "Blackcurrant Syrup",
    "Black Currant",
    "elemi",
    "Red Pepper",
    "Green Pepper",
    "Ceylon Cinnamon",
    "Cumin",
    "Cloves"
  ],
  "Fruity": [
    "Black Currant",
    "Raspberry",
    "Cherry",
    "Almond",
    "Pineapple",
    "Fig",
    "Plum",
    "Peach",
    "Coconut",
    "Melon",
    "Pomegranate",
    "Pear",
    "Apple",
    "Watermelon",
    "Hyacinth",
    "Black currant leaf",
    "Red Currant",
    "Apricot Blossom",
    "Bellflower",
    "Williams Pear",
    "Red Apple",
    "Marigold",
    "Dew Drop",
    "Red Berries",
    "Sour Cherry",
    "Black Cherry",
    "Cherry Liqueur",
    "Pistachio",
    "Pitahaya"
  ],
  "Herbal": [
    "Rosemary",
    "Basil",
    "Sage",
    "Coriander",
    "Coriander Leaf",
    "Fig Leaf",
    "Parsley",
    "Tomato Leaf",
    "Carrot Seeds",
    "Davana",
    "Artemisia",
    "Clary Sage",
    "Tarragon",
    "Thyme",
    "Magnolia Petals"
  ],
  "Floral": [
    "Rose",
    "Rosemary",
    "Sage",
    "Jasmine",
    "Lily-of-the-Valley",
    "Violet Leaf",
    "Lily",
    "Freesia",
    "Cyclamen",
    "Hibiscus",
    "Geranium",
    "Peony",
    "Magnolia",
    "Heliotrope",
    "Gardenia",
    "Turkish Rose",
    "Syringa",
    "Narcissus",
    "Lavender",
    "Violet",
    "Marigold"
  ],
  "Woody": [
    "Cedar",
    "Cypress",
    "Sandalwood",
    "Myrtle",
    "Palo Santo",
    "Virginia Cedar",
    "Labdanum",
    "Patchouli",
    "Olibanum",
    "Truffle"
  ],
  "Green": [
    "Green Almond",
    "Star Anise",
    "Fig",
    "Green Tea",
    "Green Leaves",
    "Cannabis",
    "Mint",
    "Nashi Pear",
    "Green Notes",
    "Parsley",
    "Fenugreek",
    "White Pepper"
  ],
  "Aquatic": [
    "Ozonic notes",
    "Sea Salt",
    "Watery Notes",
    "Sea Notes",
    "Water Notes"
  ],
  "Sweet": [
    "Black Tea",
    "Sweet Pea",
    "Litchi",
    "Fig Nectar",
    "Honey",
    "Moon Flower",
    "Vanilla",
    "Musk",
    "Cherry Blossom",
    "Honeysuckle",
    "Turmeric",
    "Haitian Vetiver"
,
    "Cognac",
    "Limoncello",
    "Rum",
    "citruses with sugar",
    "Caramel",
    "Marshmallow",
    "Cotton Candy",
    "Chocolate"
  ],
  "Exotic": [
    "Yuzu",
    "Cherry",
    "Pineapple",
    "Papaya",
    "Lychee",
    "Dragon Fruit",
    "Mango",
    "Passion Fruit",
    "Kiwi",
    "Pitahaya"
  ]
}

# COMMAND ----------

top_notes_mapping2 = {
    "Citrus": [
        "Yellow Mandarin",
        "Bitter Orange",
        "Pink Grapefruit",
        "Citruses",
        "Lemon Blossom",
        "Blood Orange",
        "Sweet Orange",
        "Lemon Verbena",
        "Mandarin Blossom",
        "White Bergamot",
    ],
    "Spicy": ["Ginger", "Saffron", "Pimento Leaf", "Cassia"],
    "Fruity": [
        "Pineapple Leaf",
        "Rhubarb",
        "Cassis",
        "Chinese Plum",
        "Fruity Notes",
        "Sweet Orange",
        "Bitter Almond",
    ],
    "Herbal": [
        "Mate",
        "Tagetes",
        "Angelica",
        "Chinese Tea",
        "Galbanum",
        "Nigerian Ginger",
        "Lavender Extract",
        "Chamomile",
        "Verbena",
    ],
    "Floral": [
        "Iris",
        "Tunisian Neroli",
        "Orange Blossom",
        "Lotus",
        "White Rose",
        "Turkey Red Rose",
        "Pink Freesia",
        "Jasmine Sambac",
        "Osmanthus",
        "Ylang-Ylang",
        "Bulgarian Rose",
        "Chinese Peony",
    ],
    "Woody": ["Opoponax", "Incense", "Italian Cypress", "Myrrh", "Elemi resin"],
    "Green": ["Salt", "Aldehydes", "Pineapple Leaf", "Galbanum", "Violet Leaves"],
    "Aquatic": ["Calone"],
    "Sweet": [
        "Sapodilla",
        "Aldehydes",
        "Myrrh",
        "Blood Orange",
        "Sweet Orange",
        "Bitter Almond",
    ],
    "Exotic": ["Ambrette (Musk Mallow)", "Sapodilla", "Cannabis", "Myrica", "Coffee"],
}

# COMMAND ----------

top_notes_mapping = combine_dict(top_notes_mapping1, top_notes_mapping2)

# COMMAND ----------

middle_notes_mapping1 = {
    "Floral": [
        "Peony",
        "Ambrette (Musk Mallow)",
        "Lotus",
        "Mimosa",
        "Violet Leaf",
        "Lily-of-the-Valley",
        "Geranium",
        "Magnolia",
        "Rose",
        "Tuberose",
        "Ylang-Ylang",
        "Cherry Blossom",
        "Jasmine Sambac",
        "Narcissus",
        "Hibiscus",
        "Moroccan Jasmine",
        "Pink Peony",
        "Rose Oil",
        "Cyclamen",
        "Rose Leaf",
        "Osmanthus",
        "Taif Rose",
        "Damask Rose",
        "Grasse Rose",
        "Water Jasmine",
        "Gardenia",
        "Indian Tuberose",
        "Tunisian Neroli",
        "Indian Jasmine",
        "Almond Blossom",
        "Hedione",
        "White Ginger Lily",
        "Bitter Orange",
        "Red Poppy",
        "Wisteria Flower",
        "Sweet Pea",
        "Water Lily",
        "Campion Flower",
        "Rose Water",
        "Sicilian Mandarin",
        "Blue Lavender",
        "Moroccan Rose",
    ],
    "Woody": [
        "Agarwood (Oud)",
        "Amyris",
        "Cedar",
        "Sandalwood",
        "Guaiac Wood",
        "White Wood",
        "Pine needles",
        "Virginian Cedar",
        "Vetyver",
        "Black Orchid",
        "Hinoki Wood",
    ],
    "Spicy": [
        "Cardamom",
        "Coriander",
        "Cloves",
        "Cinnamon",
        "Ginger",
        "Black Pepper",
        "Sage",
        "Saffron",
        "Thyme",
        "Nutmeg",
        "Spices",
        "Basil",
        "Cassia",
        "Caraway",
    ],
    "Citrus": [
        "Bergamot",
        "Lime",
        "Orange Leaf",
        "Mandarin Orange",
        "Grapefruit",
        "Lemon",
        "Citron",
        "Red Apple",
        "Green Almond",
        "Citruses",
    ],
    "Fresh": [
        "Watery Notes",
        "Green Accord",
        "Eucalyptus",
        "Immortelle",
        "Rain Notes",
        "Mineral notes",
        "Milk",
        "Grass",
        "Tea Leaf",
        "Solar Notes",
        "Verbena",
    ],
    "Fruity": [
        "White Peach",
        "Raspberry",
        "Black Currant",
        "Fig",
        "Strawberry",
        "Plum",
        "Peach",
        "Apricot",
        "Passionfruit",
        "Grapes",
        "Lemongrass",
        "Pineapple",
        "Persimmon",
        "Red Berries",
        "Gooseberry",
        "Litchi",
        "Hazelnut",
        "Wild Strawberry",
        "Sour Cherry",
        "Cacao",
        "Truffle",
        "Dark Chocolate",
        "Cognac",
    ],
    "Gourmand": [
        "Chocolate",
        "Vanilla",
        "Caramel",
        "Praline",
        "Coconut",
        "Coconut Milk",
        "Matcha Tea",
        "Milk",
    ],
    "Herbal": [
        "Rosemary",
        "Mate",
        "Fennel",
        "Angelica",
        "Nettle",
        "Artemisia",
        "Celery Seeds",
        "Galbanum",
    ],
    "Aromatic": [
        "Patchouli",
        "Benzoin",
        "Amber",
        "Oak moss",
        "Incense",
        "Mint",
        "Elemi",
        "Cypress",
    ],
    "Oriental": [
        "Agarwood (Oud)",
        "Narcissus",
        "Saffron",
        "Benzoin",
        "Incense",
        "Bergamot",
        "Vanilla",
        "Myrrh",
    ],
    "Aquatic": [
        "Watery Notes",
        "Mineral notes",
        "Rain Notes",
        "Sea Notes",
        "Milk",
        "Water Lily",
        "Solar Notes",
    ],
    "Chypre": [
        "Oak moss",
        "Bergamot",
        "Labdanum",
        "Papyrus",
        "Vetiver",
        "Elemi",
        "Galbanum",
    ],
    "Fougère": ["Lavender", "Geranium", "Clary Sage"],
    "Leather": ["Leather", "Suede", "Labdanum"],
    "Musk": ["Musk", "Ambrette (Musk Mallow)"],
}

middle_notes_mapping2 = {
    "Floral": ['Heliotrope', 'Black Violet', 'Orchid', 'Red Poppy', 'Blue Lavender'],
    "Woody": ['Bourbon Vetiver', 'Sandal'],
    "Fresh/Aquatic": ['Mineral notes', 'Vine'],
    "Gourmand": ['Sesame'],
    "Green/Herbal": ['heather', 'Pitosporum'],
    "Spicy": ['Ambroxan'],
    "Earthy/Spicy": ['Exotic floral notes'],
    "Citrus/Fruity": ['Black Elder', 'pink tulip']
}

# COMMAND ----------

middle_notes_mapping = combine_dict(middle_notes_mapping1, middle_notes_mapping2)

# COMMAND ----------

base_notes_mapping1 = {
    "Floral": [
        "African Orange Flower",
        "Apricot Blossom",
        "Artemisia",
        "Bellflower",
        "Bulgarian Rose",
        "Cherry Blossom",
        "Chinese Peony",
        "Chinese Plum",
        "Damask Rose",
        "Freesia",
        "Gardenia",
        "Geranium",
        "Hibiscus",
        "Hyacinth",
        "Jasmine",
        "Jasmine Sambac",
        "Lily",
        "Lily-of-the-Valley",
        "Lilac",
        "Magnolia",
        "Magnolia Petals",
        "Marigold",
        "Moon Flower",
        "Narcissus",
        "Neroli",
        "Neroli Essence",
        "Orange Blossom",
        "Osmanthus",
        "Orange Blossom",
        "Peony",
        "Rose",
        "Pomegranate Blossom",
        "Rose",
        "Syringa",
        "Tunisian Neroli",
        "Tunisian Orange Blossom",
        "Turkey Red Rose",
        "Turkish Rose",
        "Violet",
        "Violet Leaf",
        "White Flowers",
        "White Rose",
        "Ylang-Ylang",
        "Pink Freesia",
    ],
    "Citrus": [
        "Amalfi Lemon",
        "Bergamot",
        "Calabrian Mandarin",
        "Calabrian bergamot",
        "California Orange",
        "Californian Lemon",
        "Citron",
        "Clementine",
        "Grapefruit",
        "Italian Lemon",
        "Italian Mandarin",
        "Lemon",
        "Lemon Blossom",
        "Lemon Leaf",
        "Lemon Verbena",
        "Lemon Zest",
        "Lime",
        "Mandarin Blossom",
        "Mandarin Orange",
        "Nashi Pear",
        "Orange",
        "Sicilian Lemon",
        "Sicilian Mandarin",
        "Sweet Orange",
        "Tangerine",
        "Yellow Mandarin",
        "Yuzu",
        "Lemongrass",
    ],
    "Fruity": [
        "Almond",
        "Apple",
        "Apricot",
        "Black Cherry",
        "Black Currant",
        "Blackcurrant Syrup",
        "Blood Orange",
        "Cherry",
        "Coconut",
        "Fig",
        "Fig Nectar",
        "Kiwi",
        "Litchi",
        "Melon",
        "Nashi Pear",
        "Papaya",
        "Peach",
        "Pear",
        "Pineapple",
        "Plum",
        "Raspberry",
        "Red Apple",
        "Red Berries",
        "Red Currant",
        "Rhubarb",
        "Sour Cherry",
        "Strawberry",
        "Watermelon",
        "Yellow Fruits",
    ],
    "Spicy": [
        "Aldehydes",
        "Black Cardamom",
        "Black Pepper",
        "Ceylon Cinnamon",
        "Clove",
        "Coriander",
        "Coriander Leaf",
        "Ginger",
        "Green Pepper",
        "Guatemalan Cardamom",
        "Juniper",
        "Juniper Berries",
        "Mate",
        "Mint",
        "Nigerian Ginger",
        "Nutmeg",
        "Pepper",
        "Pink Pepper",
        "Sichuan Pepper",
        "Star Anise",
        "Turmeric",
        "Ginger",
    ],
    "Green/Herbal": [
        "Angelica",
        "Bamboo",
        "Basil",
        "Birch Leaf",
        "Calamansi",
        "Caraway",
        "Cassia",
        "Cyclamen",
        "Fig Leaf",
        "Green Almond",
        "Green Leaves",
        "Green Mandarin",
        "Green Notes",
        "Green Tea",
        "Hedione",
        "Lavender",
        "Lavender Extract",
        "Mint",
        "Myrtle",
        "Parsley",
        "Petitgrain",
        "Pineapple Leaf",
        "Rosemary",
        "Sage",
        "Shiso",
        "Tomato Leaf",
        "Tarragon",
        "Tea",
        "Thyme",
        "Verbena",
        "Bergamot",
        "Saffron",
    ],
    "Gourmand": [
        "Cacao",
        "Cherry Liqueur",
        "Coconut",
        "Coffee",
        "Cognac",
        "Honey",
        "Honeysuckle",
        "Lemon Zest",
        "Limoncello",
        "Pistachio",
        "Rum",
        "Caramel",
    ],
    "Woody": [
        "Cedar",
        "Elemi resin",
        "Fig",
        "Myrrh",
        "Palo Santo",
        "Sandalwood",
        "Virginia Cedar",
    ],
    "Bitter/Aromatic": [
        "Bitter Almond",
        "Bitter Orange",
        "Calone",
        "Carrot Seeds",
        "Davana",
        "Galbanum",
        "Incense",
        "Labdanum",
    ],
    "Earthy": ["Vetiver", "Myrica", "Patchouli", "Truffle"],
    "Aquatic": [
        "Dew Drop",
        "Ozonic notes",
        "Sea Notes",
        "Sea Salt",
        "Water Notes",
        "Watery Notes",
    ],
    "Powdery": ["Iris", "Powdery Notes"],
    "Musk": ["Ambrette (Musk Mallow)", "Musk"],
    "others": ["Elemi", "Salt"],
}
base_notes_mapping2 = {
  "Bitter/Aromatic": ["Licorice", "Marjoram"],
  "Earthy": ["Oakmoss", "Moss", "Haitian Vetiver", "Indonesian Patchouli Leaf", "Spanish Labdanum", "Styrax", "Benzoin", "Siam Benzoin", "Olibanum", "Vetyver", "Virginian Cedar", "Fir", "Seaweed", "Cypriol Oil or Nagarmotha", "Resin", "Lotus", "Peru Balsam", "Frankincense", "Mahogany"],
  "Floral": ["Tobacco Blossom", "Fig Tree"],
  "Fruity": ["Blackberry", "Carrot"],
  "Gourmand": ["Cotton Candy", "Cacao Pod", "White Chocolate", "Dark Chocolate", "Milk", "Mexican chocolate", "Black locust Honey"],
  "Green/Herbal": ["Cypress", "Papyrus", "Tobacco", "Cloves", "Rhuburb", "Mineral notes", "Laotian Oud", "Matcha Tea", "Rock rose"],
  "Musk": ["White Musk", "Gray Musk", "Ambrette", "Civet", "Animal notes"],
  "Powdery": ["Orris", "Heliotrope", "Powdery"],
  "Spicy": ["Vanilla", "Bourbon Vanilla", "Cashmeran", "Tobacco Leaf", "Cinnamon"],
  "Woody": ["Tonka Bean", "Amber", "Leather", "Ambergris", "Silver Pine", "Agarwood (Oud)", "Oak", "Woody Notes", "Oakmoss", "White Woods", "Birch", "Iso E Super", "White Woods", "Cedarwood", "Ebony", "Dry Wood", "Ambreine", "Tuscan Iris", "Dreamwood", "Brown sugar", "Fir Resin", "Ambretolide", "Cashmirwood", "Ebony", "Resins", "Ambrofix™", "White Wood", "Cedar Essence"]
}

base_notes_mapping = combine_dict(base_notes_mapping1, base_notes_mapping2)

# COMMAND ----------

main_accords_grouping1 = {
  "citrus": ["citrus"],
  "floral": ["floral", "white_floral", "rose", "lavender", "tuberose", "iris", "yellow_floral", "violet"],
  "woody": ["woody", "leather"],
  "spicy": ["warm_spicy", "fresh_spicy"],
  "vanilla": ["vanilla"],
  "powdery": ["powdery"],
  "sweet": ["sweet", "fruity", "almond", "cherry"],
  "musky": ["musky"],
  "fresh": ["fresh", "marine"],
  "earthy": ["earthy", "amber", "tobacco", "aquatic", "soapy", "green", "alcohol", "savory"]
}

main_accords_grouping2 = {
  "citrus": ["aldehydic"],
  "earthy": ["camphor", "conifer", "herbal", "mineral", "mossy"],
  "floral": ["anis"],
  "fresh": ["ozonic", "salty", "sour"],
  "musky": ["animalic", "metallic"],
  "powdery": ["lactonic"],
  "spicy": ["aromatic", "cinnamon", "soft_spicy"],
  "sweet": ["balsamic", "cacao", "caramel", "chocolate", "coconut", "honey", "nutty", "rum"],
  "vanilla": ["oud", "patchouli", "vanilla"],
  "woody": ["cannabis", "coffee", "smoky", "tropical"]
}
main_accords_grouping = combine_dict(main_accords_grouping1, main_accords_grouping2)
